# Generated by Django 6.0 on 2026-01-17 23:05

import base_utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_utils", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemuser",
            name="salt",
            field=models.CharField(
                default=base_utils.models.generate_salt,
                editable=False,
                help_text="Unique salt for password hashing",
                max_length=64,
            ),
        ),
    ]
