# Generated by Django 6.0 on 2026-01-17 22:55

import base_utils.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("body", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TelegramChannel",
            fields=[
                (
                    "notificationchannel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notificator.notificationchannel",
                    ),
                ),
                ("chat_id", models.CharField(max_length=100)),
                (
                    "bot_token",
                    base_utils.fields.FernetEncryptedCharField(max_length=255),
                ),
                (
                    "message_thread_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "parse_mode",
                    models.CharField(
                        choices=[
                            ("HTML", "HTML"),
                            ("Markdown", "Markdown"),
                            ("MarkdownV2", "MarkdownV2"),
                        ],
                        default="HTML",
                        max_length=20,
                    ),
                ),
                ("protect_content", models.BooleanField(default=False)),
                ("disable_notification", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("notificator.notificationchannel",),
        ),
        migrations.CreateModel(
            name="NotificatorSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "todo_notificators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="notificator_settings",
                        to="notificator.notificationchannel",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificator_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
