# Generated by Django 6.0 on 2025-12-24 23:53

import base_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notificator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramchannel",
            name="bot_token",
            field=base_utils.fields.FernetEncryptedCharField(max_length=255),
        ),
    ]
