# Generated by Django 6.0 on 2025-12-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notificator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("until", models.DateTimeField(blank=True, null=True)),
                (
                    "notificators",
                    models.ManyToManyField(
                        blank=True, to="notificator.notificationchannel"
                    ),
                ),
            ],
        ),
    ]
