# Generated by Django 6.0 on 2025-12-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todoitem",
            old_name="until",
            new_name="due_date",
        ),
    ]
