# Generated by Django 6.0 on 2025-12-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_rename_until_todoitem_due_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todoitem",
            old_name="completed",
            new_name="is_completed",
        ),
    ]
