# Generated by Django 6.0 on 2025-12-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_rename_completed_todoitem_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="notification_queued",
            field=models.BooleanField(default=False),
        ),
    ]
