# Generated by Django 6.0 on 2025-12-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_todoitem_notification_queued"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todoitem",
            options={"ordering": ["column_order", "-created_at"]},
        ),
        migrations.AddField(
            model_name="todoitem",
            name="column",
            field=models.CharField(
                choices=[
                    ("UNASSIGNED", "Unassigned"),
                    ("TO_DO", "To Do"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DONE", "Done"),
                    ("ARCHIVED", "Archived"),
                ],
                default="UNASSIGNED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="column_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
