# Generated by Django 6.0 on 2025-12-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_alter_todoitem_options_todoitem_column_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
