# Generated by Django 6.0 on 2026-01-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base_utils", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VaultEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name or label for this vault entry", max_length=255
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("password", "Password"),
                            ("token", "Token"),
                            ("ssh_key", "SSH Key"),
                        ],
                        default="password",
                        help_text="Type of secret: password, token, or SSH key",
                        max_length=20,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Optional URL associated with the entry",
                        null=True,
                    ),
                ),
                (
                    "data",
                    models.TextField(
                        help_text="E2E Encrypted secret data (password, token, or key content)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when entry was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when entry was last updated"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Optional tags to categorize and organize entries",
                        to="base_utils.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vault Entry",
                "verbose_name_plural": "Vault Entries",
                "ordering": ["-created_at"],
            },
        ),
    ]
